"""
This type stub file was generated by pyright.
"""

import sys
from collections.abc import Sequence
from typing import Any, Callable, ParamSpec
from starlette._utils import is_async_callable
from starlette.concurrency import run_in_threadpool

if sys.version_info >= (3, 10):
    ...
else:
    ...
P = ParamSpec("P")
class BackgroundTask:
    def __init__(self, func: Callable[P, Any], *args: P.args, **kwargs: P.kwargs) -> None:
        ...
    
    async def __call__(self) -> None:
        ...
    


class BackgroundTasks(BackgroundTask):
    def __init__(self, tasks: Sequence[BackgroundTask] | None = ...) -> None:
        ...
    
    def add_task(self, func: Callable[P, Any], *args: P.args, **kwargs: P.kwargs) -> None:
        ...
    
    async def __call__(self) -> None:
        ...
    


