"""
This type stub file was generated by pyright.
"""

import base64
from abc import ABC
from typing import Any, Dict, Optional, Union
from huggingface_hub.hf_api import InferenceProviderMapping
from huggingface_hub.inference._common import RequestParameters, _as_dict
from huggingface_hub.inference._providers._common import BaseConversationalTask, BaseTextGenerationTask, TaskProviderHelper, filter_none

_PROVIDER = ...
_BASE_URL = ...
class TogetherTask(TaskProviderHelper, ABC):
    """Base class for Together API tasks."""
    def __init__(self, task: str) -> None:
        ...
    


class TogetherTextGenerationTask(BaseTextGenerationTask):
    def __init__(self) -> None:
        ...
    
    def get_response(self, response: Union[bytes, Dict], request_params: Optional[RequestParameters] = ...) -> Any:
        ...
    


class TogetherConversationalTask(BaseConversationalTask):
    def __init__(self) -> None:
        ...
    


class TogetherTextToImageTask(TogetherTask):
    def __init__(self) -> None:
        ...
    
    def get_response(self, response: Union[bytes, Dict], request_params: Optional[RequestParameters] = ...) -> Any:
        ...
    


