"""
This type stub file was generated by pyright.
"""

import json
import itsdangerous
from base64 import b64decode, b64encode
from typing import Literal
from itsdangerous.exc import BadSignature
from starlette.datastructures import MutableHeaders, Secret
from starlette.requests import HTTPConnection
from starlette.types import ASGIApp, Message, Receive, Scope, Send

class SessionMiddleware:
    def __init__(self, app: ASGIApp, secret_key: str | Secret, session_cookie: str = ..., max_age: int | None = ..., path: str = ..., same_site: Literal["lax", "strict", "none"] = ..., https_only: bool = ..., domain: str | None = ...) -> None:
        ...
    
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        ...
    


